#include "render/EnvironmentMap.h"

#include "core/DescriptorAllocator.h"
#include "core/PipelineBuilder.h"
#include "core/VulkanContext.h"
#include "core/VulkanTypes.h"
#include "render/RenderTypes.h"
#include "resources/ResourceManager.h"
#include "resources/Shader.h"
#include "resources/Texture.h"

#include <stdexcept>
#include <vector>

EnvironmentMap::EnvironmentMap(VulkanContext& context, ResourceManager& resourceManager, const Texture& equirect) :
    m_context(context)
{
    const auto equirectToCubeShader = resourceManager.LoadResource<Shader>(context, "equirect_to_cube.slang", vk::ShaderStageFlags(vk::ShaderStageFlagBits::eVertex | vk::ShaderStageFlagBits::eFragment));

    if (!equirectToCubeShader)
    {
        throw std::runtime_error("EnvironmentMap: failed to load equirect_to_cube.slang");
    }

    CreateEnvironmentCube();
    CreateSampler();

    ProjectEquirectToCube(equirect, *equirectToCubeShader);
    GenerateEnvironmentMips();
}

// -----------------------------------------------------------------------------
// Initialization helpers
// -----------------------------------------------------------------------------

void EnvironmentMap::CreateEnvironmentCube()
{
    // Image. The transfer usages are for the mip chain, generated by blitting each level from the one above it.
    ImageDescription imageDesc =
    {
        .width       = k_environmentSize,
        .height      = k_environmentSize,
        .format      = k_cubeFormat,
        .usage       = vk::ImageUsageFlagBits::eColorAttachment | vk::ImageUsageFlagBits::eSampled
                     | vk::ImageUsageFlagBits::eTransferSrc    | vk::ImageUsageFlagBits::eTransferDst,
        .mipLevels   = k_environmentMips,
        .arrayLayers = 6,
        .flags       = vk::ImageCreateFlagBits::eCubeCompatible
    };

    std::tie(m_environmentImage, m_environmentMemory) = m_context.CreateImage(imageDesc);

    // Image view. Covers all six layers and the whole mip chain at once.
    ImageViewDescription viewDesc =
    {
        .image      = m_environmentImage,
        .format     = k_cubeFormat,
        .viewType   = vk::ImageViewType::eCube,
        .levelCount = k_environmentMips,
        .layerCount = 6
    };

    m_environmentView = m_context.CreateImageView(viewDesc);
}

void EnvironmentMap::CreateSampler()
{
    // No anisotropy, and ClampToEdge addressing.
    // The cube carries a full chain, read per level by the ImageBasedLighting.
    vk::SamplerCreateInfo samplerInfo
    {
        .magFilter        = vk::Filter::eLinear,
        .minFilter        = vk::Filter::eLinear,
        .mipmapMode       = vk::SamplerMipmapMode::eLinear,
        .addressModeU     = vk::SamplerAddressMode::eClampToEdge,
        .addressModeV     = vk::SamplerAddressMode::eClampToEdge,
        .addressModeW     = vk::SamplerAddressMode::eClampToEdge,
        .mipLodBias       = 0.0f,
        .anisotropyEnable = vk::False,
        .compareEnable    = vk::False,
        .compareOp        = vk::CompareOp::eAlways,
        .minLod           = 0.0f,
        .maxLod           = static_cast<float>(k_environmentMips)
    };

    m_environmentSampler = vk::raii::Sampler(m_context.GetDevice(), samplerInfo);
}

void EnvironmentMap::ProjectEquirectToCube(const Texture& equirect, const Shader& shader)
{
    // Descriptor Set 0: the equirectangular source. Texture leaves its images in eShaderReadOnlyOptimal once loaded.
    const auto descriptor = DescriptorAllocator::CreateSingleImageDescriptor(m_context, equirect.GetSampler(), equirect.GetImageView());

    // Create the graphics pipeline to project the equirect texture to the cube.
    auto [pipelineLayout, pipeline] = PipelineBuilder(m_context)
        .SetShader(shader)
        .SetDescriptorSetLayouts(*descriptor.layout)
        .SetPushConstants(vk::ShaderStageFlagBits::eFragment, sizeof(CubeFaceOrientation))
        .SetColorFormat(k_cubeFormat)
        .Build();

    // Start command recording
    const auto commandBuffer = m_context.BeginSingleTimeCommands();

    // Whole cube (all six layers): Undefined -> ColorAttachmentOptimal, ready to be rendered into.
    m_context.TransitionImageLayout(*commandBuffer,
    {
        .image          = m_environmentImage,
        .oldLayout      = vk::ImageLayout::eUndefined,
        .srcStageMask   = vk::PipelineStageFlagBits2::eTopOfPipe,
        .srcAccessMask  = vk::AccessFlagBits2::eNone,
        .newLayout      = vk::ImageLayout::eColorAttachmentOptimal,
        .dstStageMask   = vk::PipelineStageFlagBits2::eColorAttachmentOutput,
        .dstAccessMask  = vk::AccessFlagBits2::eColorAttachmentWrite,
        .layerCount     = 6
    });

    // The per-face views must stay alive until the submit completes
    std::vector<vk::raii::ImageView> faceViews;
    faceViews.reserve(6);

    const vk::Extent2D faceExtent{ k_environmentSize, k_environmentSize };

    for (uint32_t face = 0; face < 6; face++)
    {
        // Single-layer 2D view of one cube layer:
        // the cube is sampled as a cube, but rendered into one face at a time.
        ImageViewDescription faceViewDesc =
        {
            .image          = m_environmentImage,
            .format         = k_cubeFormat,
            .viewType       = vk::ImageViewType::e2D,
            .baseArrayLayer = face,
            .layerCount     = 1
        };

        faceViews.push_back(m_context.CreateImageView(faceViewDesc));

        // Configure color attachment with this faceView, no depth attachment
        vk::RenderingAttachmentInfo colorAttachment;
        colorAttachment.setImageView(*faceViews.back())
                       .setImageLayout(vk::ImageLayout::eColorAttachmentOptimal)
                       .setLoadOp(vk::AttachmentLoadOp::eClear)
                       .setStoreOp(vk::AttachmentStoreOp::eStore)
                       .setClearValue(vk::ClearColorValue(std::array<float, 4>{ 0.0f, 0.0f, 0.0f, 1.0f }));

        vk::RenderingInfo faceRenderingInfo;
        faceRenderingInfo.setRenderArea(vk::Rect2D({ 0, 0 }, faceExtent))
                         .setLayerCount(1)
                         .setColorAttachmentCount(1)
                         .setPColorAttachments(&colorAttachment);

        // Render commands for this face
        commandBuffer->beginRendering(faceRenderingInfo);

        commandBuffer->bindPipeline(vk::PipelineBindPoint::eGraphics, *pipeline);

        // Viewport/scissor are dynamic state, so they must be set
        commandBuffer->setViewport(0, vk::Viewport{ 0.0f, 0.0f, static_cast<float>(faceExtent.width), static_cast<float>(faceExtent.height), 0.0f, 1.0f });
        commandBuffer->setScissor(0, vk::Rect2D{ vk::Offset2D{ 0, 0 }, faceExtent });

        // Bind descriptor with the equirectangular texture image
        commandBuffer->bindDescriptorSets(vk::PipelineBindPoint::eGraphics, *pipelineLayout, 0, *descriptor.set, nullptr);

        // Which face this draw is painting through push constant
        commandBuffer->pushConstants<CubeFaceOrientation>(*pipelineLayout, vk::ShaderStageFlagBits::eFragment, 0, k_cubeFacesOrientation[face]);

        // Three vertices, no vertex buffer: the vertex stage builds the fullscreen triangle from SV_VertexID.
        commandBuffer->draw(3, 1, 0, 0);

        commandBuffer->endRendering();
    }

    // Whole cube: ColorAttachmentOptimal -> ShaderReadOnlyOptimal, ready for the skybox and the IBL steps.
    m_context.TransitionImageLayout(*commandBuffer,
    {
        .image          = m_environmentImage,
        .oldLayout      = vk::ImageLayout::eColorAttachmentOptimal,
        .srcStageMask   = vk::PipelineStageFlagBits2::eColorAttachmentOutput,
        .srcAccessMask  = vk::AccessFlagBits2::eColorAttachmentWrite,
        .newLayout      = vk::ImageLayout::eShaderReadOnlyOptimal,
        .dstStageMask   = vk::PipelineStageFlagBits2::eFragmentShader,
        .dstAccessMask  = vk::AccessFlagBits2::eShaderRead,
        .layerCount     = 6
    });

    m_context.EndSingleTimeCommands(*commandBuffer);
}

void EnvironmentMap::GenerateEnvironmentMips()
{
    const auto commandBuffer = m_context.BeginSingleTimeCommands();

    // Mip 0 carries the projection's output and becomes the first blit's source. Every
    // level below it has never been written, so it starts from eUndefined.
    m_context.TransitionImageLayout(*commandBuffer,
    {
        .image          = m_environmentImage,
        .oldLayout      = vk::ImageLayout::eShaderReadOnlyOptimal,
        .srcStageMask   = vk::PipelineStageFlagBits2::eFragmentShader,
        .srcAccessMask  = vk::AccessFlagBits2::eShaderRead,
        .newLayout      = vk::ImageLayout::eTransferSrcOptimal,
        .dstStageMask   = vk::PipelineStageFlagBits2::eBlit,
        .dstAccessMask  = vk::AccessFlagBits2::eTransferRead,
        .layerCount     = 6
    });

    m_context.TransitionImageLayout(*commandBuffer,
    {
        .image          = m_environmentImage,
        .oldLayout      = vk::ImageLayout::eUndefined,
        .srcStageMask   = vk::PipelineStageFlagBits2::eNone,
        .srcAccessMask  = vk::AccessFlagBits2::eNone,
        .newLayout      = vk::ImageLayout::eTransferDstOptimal,
        .dstStageMask   = vk::PipelineStageFlagBits2::eBlit,
        .dstAccessMask  = vk::AccessFlagBits2::eTransferWrite,
        .baseMipLevel   = 1,
        .levelCount     = k_environmentMips - 1,
        .layerCount     = 6
    });

    for (uint32_t mip = 1; mip < k_environmentMips; mip++)
    {
        const int32_t srcSize = static_cast<int32_t>(k_environmentSize >> (mip - 1));
        const int32_t dstSize = static_cast<int32_t>(k_environmentSize >> mip);

        // One blit per level rather than per face: both subresources span all six layers.
        vk::ImageBlit blit;
        blit.setSrcSubresource({ vk::ImageAspectFlagBits::eColor, mip - 1, 0, 6 })
            .setSrcOffsets({ vk::Offset3D{ 0, 0, 0 }, vk::Offset3D{ srcSize, srcSize, 1 } })
            .setDstSubresource({ vk::ImageAspectFlagBits::eColor, mip, 0, 6 })
            .setDstOffsets({ vk::Offset3D{ 0, 0, 0 }, vk::Offset3D{ dstSize, dstSize, 1 } });

        commandBuffer->blitImage(*m_environmentImage, vk::ImageLayout::eTransferSrcOptimal,
                                 *m_environmentImage, vk::ImageLayout::eTransferDstOptimal,
                                 blit, vk::Filter::eLinear);

        // This level is the next iteration's source, so its write must complete before that read. 
        m_context.TransitionImageLayout(*commandBuffer,
        {
            .image          = m_environmentImage,
            .oldLayout      = vk::ImageLayout::eTransferDstOptimal,
            .srcStageMask   = vk::PipelineStageFlagBits2::eBlit,
            .srcAccessMask  = vk::AccessFlagBits2::eTransferWrite,
            .newLayout      = vk::ImageLayout::eTransferSrcOptimal,
            .dstStageMask   = vk::PipelineStageFlagBits2::eBlit,
            .dstAccessMask  = vk::AccessFlagBits2::eTransferRead,
            .baseMipLevel   = mip,
            .layerCount     = 6
        });
    }

    // Whole chain: TransferSrcOptimal -> ShaderReadOnlyOptimal, ready to be sampled.
    m_context.TransitionImageLayout(*commandBuffer,
    {
        .image          = m_environmentImage,
        .oldLayout      = vk::ImageLayout::eTransferSrcOptimal,
        .srcStageMask   = vk::PipelineStageFlagBits2::eBlit,
        .srcAccessMask  = vk::AccessFlagBits2::eTransferRead | vk::AccessFlagBits2::eTransferWrite,
        .newLayout      = vk::ImageLayout::eShaderReadOnlyOptimal,
        .dstStageMask   = vk::PipelineStageFlagBits2::eFragmentShader,
        .dstAccessMask  = vk::AccessFlagBits2::eShaderRead,
        .levelCount     = k_environmentMips,
        .layerCount     = 6
    });

    m_context.EndSingleTimeCommands(*commandBuffer);
}